### ISSUE TITLE
Plugin "docusaurus-plugin-content-docs" error when adding to existing docusaurus site

### ISSUE THREAD

**Issue by xgp** [cloud-annotations/docusaurus-openapi#153]
I added the preset to my docusaurus config
```
  presets: [
    "docusaurus-preset-openapi",
    /** @type {import('docusaurus-preset-openapi').Options} */
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl:
            'https://github.com/p2-inc/phasetwo-docs/tree/master',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
```
but I get the following error when trying to run `yarn start`
```
$ yarn start
yarn run v1.22.17
$ docusaurus start
[INFO] Starting the development server...
[ERROR] Error: Plugin "docusaurus-plugin-content-docs" is used 2 times with ID "default".
To use the same plugin multiple times on a Docusaurus site, you need to assign a unique ID to each plugin instance.

The plugin ID is "default" by default. It's possible that the preset you are using already includes a plugin instance, in which case you either want to disable the plugin in the preset (to use a single instance), or assign another ID to your extra plugin instance (to use multiple instances).
    at /Users/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:20:23
    at Array.forEach (<anonymous>)
    at /Users/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:18:45
    at Array.forEach (<anonymous>)
    at ensureUniquePluginInstanceIds (/Users/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:16:35)
    at initPlugins (/Users/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:154:51)
    at loadPlugins (/Users/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:55:40)
    at load (/Users/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/server/index.js:207:113)
    at async start (/Users/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/commands/start.js:39:19)
error Command failed with exit code 1.
```
I don't understand how to "disable the plugin in the preset" as the error suggests. Has anyone encountered this? Any workarounds? Thank you!

**Comment by bourdakos1** [comment]
Hi there!

Try changing this:
```js
  presets: [
    "docusaurus-preset-openapi",
    /** @type {import('docusaurus-preset-openapi').Options} */
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl:
            'https://github.com/p2-inc/phasetwo-docs/tree/master',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
```

to this:
```js
presets: [
  "docusaurus-preset-openapi",
  /** @type {import('docusaurus-preset-openapi').Options} */
  {
    docs: {
      sidebarPath: require.resolve('./sidebars.js'),
      editUrl: 'https://github.com/p2-inc/phasetwo-docs/tree/master',
    },
    theme: {
      customCss: require.resolve('./src/css/custom.css'),
    },
  },
],
```

**Comment by xgp** [comment]
Hi @bourdakos1 thanks for the response. After I nested it in another array, it works fine:

```
  presets: [
    [
      "docusaurus-preset-openapi",
      /** @type {import('docusaurus-preset-openapi').Options} */
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl:
          'https://github.com/p2-inc/phasetwo-docs/tree/master',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
```
